# Generated by Django 3.2.6 on 2021-08-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.TextField(editable=False),
        ),
    ]
